Library/Pages/Book/Detail.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class DetailModel : PageModel
    {
        public LibraryCore.Models.Book Book { get; set; }

        private readonly IUnitOfWork _unitOfWork;
        public DetailModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet(int id)
        {
            Book = _unitOfWork.BookRepository.Find(id);
        }
    }
}

Library/Pages/Book/Search.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.Book
{
    public class SearchModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public SearchModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IList<LibraryCore.Models.Book> Books { get; set; }
        public IList<Category> Categories { get; set; }

        public void OnGet(int? cid, int? pages,string? name)
        {
            Categories = _unitOfWork.CategoryRepository.GetAll();
            var all = _unitOfWork.BookRepository.GetAll().Where(x=>x.Status.Value).ToList();
            if (cid.HasValue)
            {
                all = all.Where(x => x.CategoryId == cid).ToList();
            }
            if (!pages.HasValue)
            {
                pages = 1;
            }

            if (!String.IsNullOrEmpty(name))
            {
                all = all.Where(x =>
                    x.Title.ToLower().Contains(name.ToLower()) || x.Author.Fullname.ToLower().Contains(name.ToLower()) ).ToList();
            }

            ViewData["idValue"] = cid;
            ViewData["pages"] = pages;
            ViewData["search"] = name;
            ViewData["countPage"] = Math.Ceiling( all.Count/3d);
            Books = all.Skip((pages.Value-1) * 3).Take(3).ToList();
        }
    }
}

Library/Pages/Cart.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class CartModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public CartModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public ICollection<Cart> Carts { get; set; } = default!;

        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public double Total { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("Index");
            }
            Carts = _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value);
            return Page();
        }

        public IActionResult OnGetDeleteCart(int cartId)
        {
            _unitOfWork.CartRepository.Delete(cartId);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }

        public IActionResult OnGetAddCart(int bookId)
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("Index");
            }
            Cart cart = _unitOfWork.CartRepository.FindByBookIdAndUserId(bookId, HttpContext.Session.GetInt32("userid").Value);
            if (cart != null)
            {
                cart.Quantity += 1;
                _unitOfWork.CartRepository.Update(cart);
                _unitOfWork.SaveChange();
            }
            else
            {
                _unitOfWork.CartRepository.Add(new Cart
                {
                    BookId = bookId,
                    Quantity = 1,
                    UserId = HttpContext.Session.GetInt32("userid").Value
                });
                _unitOfWork.SaveChange();
                HttpContext.Session.SetInt32("cartcount", _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value).Count);
            }
            return RedirectToPage("Index");

        }

        public IActionResult OnGetAddQuantity(int cartId)
        {
            Cart cart = _unitOfWork.CartRepository.FindCartByIdWithNav(cartId);
            if (cart != null)
            {
                cart.Quantity += 1;
                _unitOfWork.CartRepository.Update(cart);
                _unitOfWork.SaveChange();
                return new JsonResult(cart);
            }

            return Page();
        }

        public IActionResult OnGetMinusQuantity(int cartId)
        {
            Cart cart = _unitOfWork.CartRepository.FindCartByIdWithNav(cartId);
            if (cart != null)
            {
                if (cart.Quantity == 1)
                {
                    _unitOfWork.CartRepository.Delete(cart);
                    _unitOfWork.SaveChange();
                    HttpContext.Session.SetInt32("cartcount", _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value).Count);
                    cart.Quantity = 0;
                    return new JsonResult(cart);
                }
                else
                {
                    cart.Quantity -= 1;
                    _unitOfWork.CartRepository.Update(cart);
                    _unitOfWork.SaveChange();
                    return new JsonResult(cart);
                }
            }

            return Page();
        }
        public IActionResult OnPost()
        {
            Carts = _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value);
            Order order = new Order
            {
                UserId = HttpContext.Session.GetInt32("userid").Value,
                Address = Address,
                OrderDate = DateTime.Now,
                Total = Total,
                Status = "Pending"
            };
            _unitOfWork.OrderRepository.Add(order);
            _unitOfWork.SaveChange();
            foreach (var item in Carts)
            {
                _unitOfWork.OrderDetailRepository.Add(new OrderDetail
                {
                    OrderId = order.OrderId,
                    BookId = item.BookId,
                    Quantity = item.Quantity
                });
                _unitOfWork.SaveChange();

            }
            _unitOfWork.CartRepository.DeleteAllByUserId(HttpContext.Session.GetInt32("userid").Value);
            HttpContext.Session.SetInt32("cartcount", 0);
            _unitOfWork.SaveChange();

            return RedirectToPage("Index");
        }
    }
}

Library/Pages/Book/Detail.cshtml
@page "/Book/Detail/{id:int}"
@model Library.Pages.DetailModel
@{
    var idValue = Request.RouteValues["id"]?.ToString();
}
<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Book</a>
                <span class="breadcrumb-item active">Book Detail</span>
            </nav>
        </div>
    </div>
</div>
<div class="container-fluid pb-5">
    <div class="row px-xl-5">
        <div class="col-lg-5 mb-30">
            <div id="product-carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner bg-light">
                    <div class="carousel-item active">
                        <img class="w-100 h-100" src="@Model.Book.Image" alt="Image">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-lg-7 h-auto mb-30">
            <div class="h-100 bg-light p-30">
                <h3>@Model.Book.Title</h3>
                <div class="d-flex mb-3">
                    <div class="text-primary mr-2">
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star"></small>
                        <small class="fas fa-star-half-alt"></small>
                        <small class="far fa-star"></small>
                    </div>
                    <small class="pt-1">(99 Reviews)</small>
                </div>
                <!--<h3 class="font-weight-semi-bold mb-4">$150.00</h3>-->
                <p class="mb-4">@Model.Book.Introduction</p>
                Publisher:<p class="mb-4">@Model.Book.Publisher</p>
                Publication Date:<p class="mb-4">@Model.Book.PublicationDate</p>

                <div class="d-flex align-items-center mb-4 pt-2">
                    <strong class="text-dark mr-3">Quantity:</strong>
                    <div class="input-group quantity mr-3" style="width: 130px;">
                        <input type="text" class="form-control bg-secondary border-0 text-center" value="1">
                    </div>
                    <a class="btn btn-primary px-3" asp-page="/Cart" asp-page-handler="AddCart" asp-route-bookId="@Model.Book.BookId">
                        <i class="fa fa-shopping-cart mr-1"></i> Add To
                        Cart
                    </a>
                    <button class="btn btn-primary px-3">
                        <i class="far fa-heart mr-1"></i> Add To
                        Reservations List
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="row px-xl-5">
        <div class="col">
            <div class="bg-light p-30">
                <div class="nav nav-tabs mb-4">
                    <a class="nav-item nav-link text-dark active" data-toggle="tab" href="#tab-pane-1">Description</a>
                    <a class="nav-item nav-link text-dark" data-toggle="tab" href="#tab-pane-3">Reviews (1)</a>
                </div>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="tab-pane-1">
                        <h4 class="mb-3">Book Description</h4>
                        <p>@Model.Book.Description</p>
                    </div>
                    <div class="tab-pane fade" id="tab-pane-2">
                        <h4 class="mb-3">Additional Information</h4>
                        <p>Eos no lorem eirmod diam diam, eos elitr et gubergren diam sea. Consetetur vero aliquyam invidunt duo dolores et duo sit. Vero diam ea vero et dolore rebum, dolor rebum eirmod consetetur invidunt sed sed et, lorem duo et eos elitr, sadipscing kasd ipsum rebum diam. Dolore diam stet rebum sed tempor kasd eirmod. Takimata kasd ipsum accusam sadipscing, eos dolores sit no ut diam consetetur duo justo est, sit sanctus diam tempor aliquyam eirmod nonumy rebum dolor accusam, ipsum kasd eos consetetur at sit rebum, diam kasd invidunt tempor lorem, ipsum lorem elitr sanctus eirmod takimata dolor ea invidunt.</p>
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item px-0">
                                        Sit erat duo lorem duo ea consetetur, et eirmod takimata.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Amet kasd gubergren sit sanctus et lorem eos sadipscing at.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Duo amet accusam eirmod nonumy stet et et stet eirmod.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Takimata ea clita labore amet ipsum erat justo voluptua. Nonumy.
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item px-0">
                                        Sit erat duo lorem duo ea consetetur, et eirmod takimata.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Amet kasd gubergren sit sanctus et lorem eos sadipscing at.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Duo amet accusam eirmod nonumy stet et et stet eirmod.
                                    </li>
                                    <li class="list-group-item px-0">
                                        Takimata ea clita labore amet ipsum erat justo voluptua. Nonumy.
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="tab-pane-3">
                        <div class="row">
                            <div class="col-md-6">
                                <h4 class="mb-4">1 review for "Dance with the Devil"</h4>
                                <div class="media mb-4">
                                    <img src="img/user.jpg" alt="Image" class="img-fluid mr-3 mt-1" style="width: 45px;">
                                    <div class="media-body">
                                        <h6>John Doe<small> - <i>01 Jan 2045</i></small></h6>
                                        <div class="text-primary mb-2">
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star"></i>
                                            <i class="fas fa-star-half-alt"></i>
                                            <i class="far fa-star"></i>
                                        </div>
                                        <p>Diam amet duo labore stet elitr ea clita ipsum, tempor labore accusam ipsum et no at. Kasd diam tempor rebum magna dolores sed sed eirmod ipsum.</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <h4 class="mb-4">Leave a review</h4>
                                <small>Your email address will not be published. Required fields are marked *</small>
                                <div class="d-flex my-3">
                                    <p class="mb-0 mr-2">Your Rating * :</p>
                                    <div class="text-primary">
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                        <i class="far fa-star"></i>
                                    </div>
                                </div>
                                <form>
                                    <div class="form-group">
                                        <label for="message">Your Review *</label>
                                        <textarea id="message" cols="30" rows="5" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group mb-0">
                                        <input type="submit" value="Leave Your Review" class="btn btn-primary px-3">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->

Library/Pages/Book/Search.cshtml
@page

@model Library.Pages.Book.SearchModel
@{
    var idValue = ViewData["idValue"];
    var pages = (int)ViewData["pages"];
    var search = ViewData["search"];
    var countPage = (double)ViewData["countPage"] ;
}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Books</a>
                <span class="breadcrumb-item active">Books List</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Shop Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-4">
            <!-- Price Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Filter by Category</span></h5>
            <div class="bg-light p-4 mb-30">
                <form id='f1' action="/Book/Search" method="GET">
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" name="cid" id="book-all">
                        <label class="custom-control-label" for="book-all">All Books</label>

                    </div>

                    @foreach (var item in Model.Categories)
                    {

                        <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                            <input type="checkbox" class="custom-control-input" id="book-@item.CategoryId" name="cid" value="@item.CategoryId">
                            <label class="custom-control-label" for="book-@item.CategoryId">@item.CategoryName</label>
                        </div>
                    }

                    <input type="submit" class="btn btn-block btn-primary font-weight-bold my-3 py-3" value="Filter">
                </form>
            </div>
            <!-- Price End -->

        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">


                @foreach (var item in Model.Books)
                {
                    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                        <div class="product-item bg-light mb-4">
                            <div class="product-img position-relative overflow-hidden">
                                <img class="img-fluid w-100" src="@item.Image" alt="">
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href="appointmentListCart?action=addToCart&bookId=${bookAuthor.book.id}"><i class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href="myReservation?action=addToReservationList&bookId=${bookAuthor.book.id}"><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" asp-page="Detail" asp-route-id="@item.BookId">@item.Title</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>@item.Author.Fullname</h5>
                                </div>
                                <div class="d-flex align-items-center justify-content-center mb-1">
                                    @for (int i = 1; i <= item.Rate; i++)
                                    {
                                        <small class="fa fa-star text-primary mr-1"></small>
                                    }
                                </div>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <small>@item.Quantity left</small>
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div class="col-12">
                    <nav>

                        <ul class="pagination justify-content-center">
                            <li class="page-item previous"><a class="page-link" asp-page="/Book/Search" asp-route-pages="@(pages-1)" asp-route-cid="@idValue" asp-route-name="@search">Previous</a></li>
                            @for (int i = 1; i <= @countPage; i++)
                            {
                                <li class="page-item number"><a class="page-link" asp-page="/Book/Search" asp-route-pages="@i" asp-route-cid="@idValue" asp-route-name="@search">@i</a></li>
                            }
                            <li class="page-item next"><a class="page-link" asp-page="/Book/Search" asp-route-pages="@(pages+1)" asp-route-cid="@idValue" asp-route-name="@search">Next</a></li>

                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

<script>
    var id = '@idValue'
    if (id == '') {
        document.querySelector('#book-all').checked = true;
    }
    else {
        document.querySelector('#book-all').checked = false;
        var selectedId = "#book-" + id;
        document.querySelector(selectedId).checked = true;
    }
    
    var pageIndex = '@pages'
    if(pageIndex == 1 || pageIndex == '') {
        document.querySelector('.page-item.previous').classList.add('disabled')
    }
    else if(pageIndex >= @countPage){
        document.querySelector('.page-item.next').classList.add('disabled')
    }
    else{
        document.querySelector('.page-item.number').classList.add('active')
    }

</script>

<!--Script Handle Sidebar-->
<script>
    function myFunction(obj) {
        var checkBox = document.getElementsByName("cid");
        console.log(1);
        if ((obj.id == 'book-all') && (checkBox[0].checked == true)) {
            for (var i = 1; i < checkBox.length; i++) {
                checkBox[i].checked = false;
            }
        } else {
            for (var i = 1; i < checkBox.length; i++) {
                if (checkBox[i].checked == true)
                    checkBox[0].checked = false;
            }
        }

        for (var i = 0; i < checkBox.length; i++) {
            if (checkBox[i].checked == true) {
                for (var z = 0; z < checkBox.length; z++) {
                    checkBox[z].checked = false;
                }
                checkBox[i].checked = true
                break;
            }
        }
    }
</script>
<!--End Script Handle Sidebar
-->