Library/Pages/Admin/AccountManagement.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.Admin
{
    public class AccountManagementModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public AccountManagementModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public User User { get; set; }
        public IList<User> Users { get; set; }

        public void OnGet()
        {
            Users = _unitOfWork.UserRepository.GetAll();

        }

        public IActionResult OnPostEditUser()
        {
            int userId = int.Parse(Request.Form["id"]);
            string role = Request.Form["role"];
            string status = Request.Form["status"];
            User u = _unitOfWork.UserRepository.Find(userId);
            u.UserRole = role;
            u.Status = bool.Parse(status);
            _unitOfWork.UserRepository.Update(u);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }
        public IActionResult OnPostAddUser()
        {
            _unitOfWork.UserRepository.Add(User);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }
    }
}

Library/Pages/Admin/BookManagement.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Build.Framework;

namespace Library.Pages.Admin
{
    public class BookManagementModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public BookManagementModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IList<Category> Categories { get; set; }
        public IList<LibraryCore.Models.Book> Books { get; set; }
        public IList<Author> Authors { get; set; }
        

        [BindProperty]
        public LibraryCore.Models.Book Book { get; set; }

        [Required]
        public IFormFile Image { get; set; }
        public void OnGet()
        {
            Categories = _unitOfWork.CategoryRepository.GetAll();
            Books = _unitOfWork.BookRepository.GetAll();
            Authors = _unitOfWork.AuthorRepository.GetAll();
        }

        public IActionResult OnPostEditBook()
        {
            LibraryCore.Models.Book b = _unitOfWork.BookRepository.Find(int.Parse(Request.Form["id"]));
            b.Title = Request.Form["title"];
            b.Description = Request.Form["description"];
            b.CategoryId = int.Parse(Request.Form["category"]);
            b.Publisher = Request.Form["publisher"];
            b.PublicationDate = DateTime.Parse(Request.Form["date"]);
            b.Quantity = int.Parse(Request.Form["quantity"]);
            var file = Request.Form.Files["newimage"];

            if (file != null && file.Length > 0)
            {
                var fileName = file.FileName;
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "books", fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                b.Image = "/img/books/" + fileName;
            }
            b.Rate = int.Parse(Request.Form["rate"]);
            b.Introduction = Request.Form["introduction"];
            _unitOfWork.BookRepository.Update(b);
            _unitOfWork.SaveChange();
            return RedirectToPage();

        }

        public IActionResult OnPostAddBook()
        {
            var fileName = Image.FileName;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "books", fileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(stream);
            }
            Book.Image = "/img/books/" + fileName;
            _unitOfWork.BookRepository.Add(Book);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }
        public IActionResult OnGetExportFile()
        {
            var data = _unitOfWork.BookRepository.GetAll().ToList(); // Lấy dữ liệu từ Backend
            MemoryStream memoryStream = new MemoryStream();
            StreamWriter streamWriter = new StreamWriter(memoryStream);
            streamWriter.WriteLine("BookId," + "Title," + "Publisher," + "PublicationDate," + "Quantity," + "Rate," + "Introduction");
            // Ghi dữ liệu vào tập tin
            foreach (var item in data)
            {
                streamWriter.WriteLine(item.BookId + "," + item.Title + "," + item.Publisher + "," + item.PublicationDate + "," + item.Quantity + "," + item.Rate+","+item.Introduction);
            }
            streamWriter.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            // Trả về tập tin đã tạo
            return File(memoryStream, "text/csv", "Books.csv");
        }
    }
}

Library/Pages/Admin/CategoryManagement.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Text;
using Humanizer.Localisation.TimeToClockNotation;
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.Admin
{
    public class CategoryManagementModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryManagementModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public string mess { get; set; }
        public IList<Category> Categories { get; set; }
        [BindProperty]
        public Category Category { get; set; }

        [Required]
        public IFormFile Image { get; set; }
        public void OnGet()
        {
            Categories = _unitOfWork.CategoryRepository.GetAll().ToList();

        }

        public IActionResult OnPostEditCategory()
        {
            Category c = _unitOfWork.CategoryRepository.Find(int.Parse(Request.Form["id"]));
            c.CategoryName = Request.Form["name"];
            var file = Request.Form.Files["newimage"];

            if (file != null && file.Length > 0)
            {
                var fileName = file.FileName;
                var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "category", fileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                c.Image = "/img/category/" + fileName;

            }
            _unitOfWork.CategoryRepository.Update(c);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }

        public IActionResult OnPostAddCategory()
        {
            var fileName = Image.FileName;
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "img", "category", fileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(stream);
            }
            Category.Image = "/img/category/" + fileName;
            _unitOfWork.CategoryRepository.Add(Category);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }

        public IActionResult OnGetDeleteCategory(int categoryId)
        {
            try
            {
                _unitOfWork.CategoryRepository.Delete(categoryId);
                _unitOfWork.SaveChange();
                return new JsonResult("1");

            }
            catch (Exception e)
            {
                return new JsonResult("0");

            }

        }
        public IActionResult OnGetExportFile()
        {
            var data = _unitOfWork.CategoryRepository.GetAll().ToList(); // Lấy dữ liệu từ Backend
            MemoryStream memoryStream = new MemoryStream();
            StreamWriter streamWriter = new StreamWriter(memoryStream);

            streamWriter.WriteLine("CategoryId," + "CategoryName");
            // Ghi dữ liệu vào tập tin
            foreach (var item in data)
            {
                streamWriter.WriteLine(item.CategoryId + "," + item.CategoryName);
            }
            streamWriter.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            // Trả về tập tin đã tạo
            return File(memoryStream, "text/csv", "categories.csv");
        }
        public string ImportMessage { get; set; }

        public async Task<IActionResult> OnPostImportFile(IFormFile csvFile)
        {
            if (csvFile == null || csvFile.Length == 0)
            {
                ImportMessage = "No file selected.";
                return RedirectToPage();
            }

            using (var reader = new StreamReader(csvFile.OpenReadStream(), Encoding.UTF8))
            {
                // Đọc dữ liệu từ tập tin CSV
                var csvData = await reader.ReadToEndAsync();
                List<Category> chiatay = new List<Category>();
                List<Category> all = _unitOfWork.CategoryRepository.GetAll().ToList();
                var lines = csvData.Split("\n");
                for (int i = 1; i < lines.Length; i++)
                {
                    Category c;
                    var line = lines[i].Trim();
                    if (line == "")
                    {
                        break;
                    }
                    var value = line.Split(',');
                    if (all.FirstOrDefault(x => x.CategoryId == int.Parse(value[0])) == null)
                    {
                        c = new Category
                        {
                            CategoryName = value[1],
                            Image = ""
                        };
                        _unitOfWork.CategoryRepository.Add(c);
                        _unitOfWork.SaveChange();
                    }
                }

                ImportMessage = "File imported successfully.";
            }

            return RedirectToPage();
        }
    }
}

Library/Pages/Admin/Dashboard.cshtml.cs
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.Admin
{
    public class DashboardModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public DashboardModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public int CountUser { get; set; }
        public int CountBook { get; set; }
        public int CountOrder { get; set; }
        public int[] OrdersByMonth { get; set; }
        public void OnGet()
        {
            OrdersByMonth = _unitOfWork.OrderRepository.CountOrdersByMonth();
            CountUser = _unitOfWork.UserRepository.GetAll().Count;
            CountOrder = _unitOfWork.OrderRepository.GetAll().Count;
            CountBook = _unitOfWork.BookRepository.GetAll().Count;
        }
    }
}

Library/Pages/Admin/OrderManagement.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages.Admin
{
    public class OrderManagementModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderManagementModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IList<Order> Orders { get; set; }

        public void OnGet()
        {
            Orders = _unitOfWork.OrderRepository.GetAllOrdersNav();
        }

        public IActionResult OnGetOrderDetails(int orderId)
        {
            var order = _unitOfWork.OrderRepository.GetAllOrdersNav()
                .FirstOrDefault(o => o.OrderId == orderId);

            if (order == null)
            {
                return NotFound();
            }
            return Partial("_OrderDetailsPartial", order.OrderDetails);
        }

        public IActionResult OnPostEditOrder()
        {
            int orderId = int.Parse(Request.Form["id"]);
            string address = Request.Form["address"];
            string status = Request.Form["status"];
            Order o = _unitOfWork.OrderRepository.Find(orderId);
            o.Address = address;
            o.Status = status;
            _unitOfWork.OrderRepository.Update(o);
            _unitOfWork.SaveChange();
            return RedirectToPage();

        }
        public IActionResult OnGetExportFile()
        {
            var data = _unitOfWork.OrderRepository.GetAll().ToList(); // Lấy dữ liệu từ Backend
            MemoryStream memoryStream = new MemoryStream();
            StreamWriter streamWriter = new StreamWriter(memoryStream);
            streamWriter.WriteLine("OrderId," + "UserId," + "OrderDate," + "Status," + "Address," + "Total");
            // Ghi dữ liệu vào tập tin
            foreach (var item in data)
            {
                streamWriter.WriteLine(item.OrderId + "," + item.UserId+","+item.OrderDate+","+item.Status+","+item.Address+","+item.Total);
            }
            streamWriter.Flush();
            memoryStream.Seek(0, SeekOrigin.Begin);

            // Trả về tập tin đã tạo
            return File(memoryStream, "text/csv", "Orders.csv");
        }
    }
}

Library/Pages/Admin/CategoryManagement.cshtml
@page
@model Library.Pages.Admin.CategoryManagementModel
@using System.Text.Json
@using System.Text.Json.Serialization
@{
    Layout = "Shared/_LayoutAdmin";

}
<div id="main">
    <header class="mb-3">
        <a href="#" class="burger-btn d-block d-xl-none">
            <i class="bi bi-justify fs-3"></i>
        </a>
    </header>

    <div class="page-heading">
        <div class="page-title">
            <div class="row">
                <div class="col-12 col-md-6 order-md-1 order-last">
                    <h3>Category Management</h3>
                </div>
                <div class="col-12 col-md-6 order-md-2 order-first">
                    <nav aria-label="breadcrumb" class="breadcrumb-header float-start float-lg-end">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="dashboard">Dashboard</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Category Management</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <section class="section">
            <div class="card">
                <div class="card-header">
                    @* <form asp-page="/Admin/CategoryManagement" asp-page-handler="ExportFile" method="POST"> *@
                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalAdd">Add a new category</button>
                    <button onclick="exportData()" class="btn btn-primary">Export file</button><br/><br/>

                    <form method="post" asp-page-handler="ImportFile" enctype="multipart/form-data">
                        <input type="file" name="csvFile" />
                        <button type="submit">Import</button>
                    </form>
                </div>

                @if (!string.IsNullOrEmpty(Model.ImportMessage))
                {
                    <p>@Model.ImportMessage</p>
                }
                <div class="card-body">
                    <table class="table table-striped" id="table1">
                        <thead>
                            <tr>
                                <th>Category ID</th>
                                <th>Category Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach (var item in Model.Categories)
                            {
                                <tr>

                                    <td>@item.CategoryId</td>
                                    <td>
                                        @item.CategoryName
                                    </td>
                                    <td>
                                        <!--Modal trigger-->
                                        <a data-toggle="modal" data-target="#modalEdit" class='sidebar-link clickingEdit' data-categoryid="@item.CategoryId" data-categoryname="@item.CategoryName" data-image="@item.Image">
                                            <i class="fa fa-pencil"></i>

                                        </a>
                                        &nbsp;
                                        <a data-toggle="modal" data-target="#modalView" class='sidebar-link clickingView' data-categoryid="@item.CategoryId" data-categoryname="@item.CategoryName" data-image="@item.Image">

                                            <i class="fa fa-eye"></i>
                                        </a>
                                        @* <a class="deleteBtn" data-categoryId="@item.CategoryId">

                                    <i class="fa fa-trash"></i>
                                    </a> *@

                                        <!-- End Modal trigger -->
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </section>
    </div>


</div>


<div class="modal hide fade" id="modalEdit">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <form asp-page="/Admin/CategoryManagement" asp-page-handler="EditCategory" method="POST" enctype="multipart/form-data">
                <input type="hidden" id="categoryid" name="id">
                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edit Category</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label for="categoryname" class="col-form-label">Category Name:</label>
                        <input type="text" class="form-control" id="categoryname" name="name">
                    </div>
                    <div class="form-group">
                        <label for="image" class="col-form-label">Image:</label>
                        <img class="form-control" id="image" name="image" style="height: fit-content" />
                        <input type="file" name="newimage" id="newimage">
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal hide fade" id="modalView">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">


            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">User Information</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <div class="form-group">
                    <label for="categoryname" class="col-form-label">Category Name:</label>
                    <input type="text" class="form-control" id="categorynames" name="name" disabled>
                </div>
                <div class="form-group">
                    <label for="image" class="col-form-label">Image:</label>
                    <img class="form-control" id="images" name="image" style="height: fit-content" />
                </div>

            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

<div class="modal hide fade" id="modalAdd">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">


            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Add a new category</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <form asp-page="/Admin/CategoryManagement" asp-page-handler="AddCategory" method="POST" enctype="multipart/form-data">

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="form-group">
                        <label asp-for="Category.CategoryName" class="col-form-label"></label>
                        <input asp-for="Category.CategoryName" class="form-control">

                    </div><div class="form-group">
                        <label asp-for="Image" class="col-form-label"></label>
                        <input asp-for="Image" class="form-control">

                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <input type="submit" value="Add" class="btn btn-primary" />
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </form>

        </div>
    </div>
</div>

<script>
    // Simple Datatable
    let table1 = document.querySelector('#table1');
    let dataTable = new simpleDatatables.DataTable(table1);
</script>
<script>
    $(document).ready(function () {
        $(".clickingEdit").click(function () { // Click to only happen on announce links
            $("#image").attr("src", $(this).data('image'));
            $("#categoryname").val($(this).data('categoryname'));
            $("#categoryid").val($(this).data('categoryid'));
            $('#modalEdit').modal('show');
        });
    });
</script>



<script>
    $(document).ready(function () {
        $(".clickingView").click(function () { // Click to only happen on announce links
            $("#categorynames").val($(this).data('categoryname'));
            $("#categoryid").val($(this).data('categoryid'));
            $("#images").attr("src", $(this).data('image'));

            $('#modalView').modal('show');
        });
    });
</script>
<script>
    function exportData() {
        fetch('/Admin/CategoryManagement?handler=ExportFile')
            .then(response => {
                if (!response.ok) {
                    throw new Error('Export failed');
                }
                return response.blob();
            })
            .then(blob => {
                var url = window.URL.createObjectURL(blob);
                var a = document.createElement('a');
                a.href = url;
                a.download = 'data.csv';
                document.body.appendChild(a);
                a.click();
                document.body.removeChild(a);
            })
            .catch(error => {
                console.error('Export failed:', error);
                alert('Export failed. Please try again later.');
            });
    }
</script>
<script>
    @* $(document).ready(function () {
        $(".deleteBtn").click(function () { // Click to only happen on announce links
        const categoryId = $(this).data('categoryid');

        $.ajax({
        url: '/Admin/CategoryManagement?handler=DeleteCategory',
        type: 'GET',
        data: { categoryId: categoryId },
        success: function (response) {
        if(response == "1"){
        alert("Delete successfully!");
        location.reload();
        }
        else{
        alert("Category is being used!");
        }
        },
        error: function (xhr, status, error) {
        console.error(error);
        }

        });
        });
        }); *@
</script>

Library/Pages/Admin/Dashboard.cshtml
@page
@using System.Text.Json
@model Library.Pages.Admin.DashboardModel
@{
    Layout = "Shared/_LayoutAdmin";
    var x = JsonSerializer.Serialize(Model.OrdersByMonth);
}
<div id="main" style="background-color: #f2f7ff;">
    <header class="mb-3">
        <a href="#" class="burger-btn d-block d-xl-none">
            <i class="bi bi-justify fs-3"></i>
        </a>
    </header>

    <div class="page-heading">
        <h3>Dashboard Statistics</h3>
    </div>
    <div class="page-content">
        <section class="row">
            <!--nhan-->
            <div class="col-12 col-lg-9">
                <div class="row">
                    <div class="col-6 col-lg-4 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon purple">
                                            <i class="iconly-boldShow"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Total Books</h6>
                                        <h6 class="font-extrabold mb-0">@Model.CountBook</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-lg-4 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon blue">
                                            <i class="iconly-boldProfile"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Total Users</h6>
                                        <h6 class="font-extrabold mb-0">@Model.CountUser</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 col-lg-4 col-md-6">
                        <div class="card">
                            <div class="card-body px-3 py-4-5">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="stats-icon green">
                                            <i class="iconly-boldAdd-User"></i>
                                        </div>
                                    </div>
                                    <div class="col-md-8">
                                        <h6 class="text-muted font-semibold">Orders Today</h6>
                                        <h6 class="font-extrabold mb-0">@Model.CountOrder</h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h4>Number of orders monthly</h4>
                            </div>
                            <div class="card-body">
                                <div id="chart"></div>
                                <script src="/js/apexcharts.min.js"></script>
                                <script>
                                    var codesJS = new Array();
                                    var codes = @Html.Raw(x);
                                    if (codes != null) {
                                        for (var i = 0; i < codes.length; i++) {
                                            var code = codes[i];
                                            codesJS[i] = code;
                                        }
                                    }
                                    var options = {
                                        annotations: {
                                            position: 'back'
                                        },
                                        dataLabels: {
                                            enabled: false
                                        },
                                        chart: {
                                            type: 'bar',
                                            height: 300
                                        },
                                        fill: {
                                            opacity: 1
                                        },
                                        plotOptions: {
                                        },
                                        series: [{
                                            name: 'orders',
                                            data: codesJS
                                        }],
                                        colors: '#435ebe',
                                        xaxis: {
                                            categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                                        },
                                    };

                                    var chart = new ApexCharts(document.querySelector("#chart"), options);
                                    chart.render();
                                </script>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- het nhan-->
        </section>
    </div>


</div>