Library/Pages/Cart.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class CartModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public CartModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        [BindProperty]
        public ICollection<Cart> Carts { get; set; } = default!;

        [BindProperty]
        public string Address { get; set; }
        [BindProperty]
        public double Total { get; set; }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("Index");
            }
            Carts = _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value);
            return Page();
        }

        public IActionResult OnGetDeleteCart(int cartId)
        {
            _unitOfWork.CartRepository.Delete(cartId);
            _unitOfWork.SaveChange();
            return RedirectToPage();
        }

        public IActionResult OnGetAddCart(int bookId)
        {
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("Index");
            }
            Cart cart = _unitOfWork.CartRepository.FindByBookIdAndUserId(bookId, HttpContext.Session.GetInt32("userid").Value);
            if (cart != null)
            {
                cart.Quantity += 1;
                _unitOfWork.CartRepository.Update(cart);
                _unitOfWork.SaveChange();
            }
            else
            {
                _unitOfWork.CartRepository.Add(new Cart
                {
                    BookId = bookId,
                    Quantity = 1,
                    UserId = HttpContext.Session.GetInt32("userid").Value
                });
                _unitOfWork.SaveChange();
                HttpContext.Session.SetInt32("cartcount", _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value).Count);
            }
            return RedirectToPage("Index");

        }

        public IActionResult OnGetAddQuantity(int cartId)
        {
            Cart cart = _unitOfWork.CartRepository.FindCartByIdWithNav(cartId);
            if (cart != null)
            {
                cart.Quantity += 1;
                _unitOfWork.CartRepository.Update(cart);
                _unitOfWork.SaveChange();
                return new JsonResult(cart);
            }

            return Page();
        }

        public IActionResult OnGetMinusQuantity(int cartId)
        {
            Cart cart = _unitOfWork.CartRepository.FindCartByIdWithNav(cartId);
            if (cart != null)
            {
                if (cart.Quantity == 1)
                {
                    _unitOfWork.CartRepository.Delete(cart);
                    _unitOfWork.SaveChange();
                    HttpContext.Session.SetInt32("cartcount", _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value).Count);
                    cart.Quantity = 0;
                    return new JsonResult(cart);
                }
                else
                {
                    cart.Quantity -= 1;
                    _unitOfWork.CartRepository.Update(cart);
                    _unitOfWork.SaveChange();
                    return new JsonResult(cart);
                }
            }

            return Page();
        }
        public IActionResult OnPost()
        {
            Carts = _unitOfWork.CartRepository.FindByUserId(HttpContext.Session.GetInt32("userid").Value);
            Order order = new Order
            {
                UserId = HttpContext.Session.GetInt32("userid").Value,
                Address = Address,
                OrderDate = DateTime.Now,
                Total = Total,
                Status = "Pending"
            };
            _unitOfWork.OrderRepository.Add(order);
            _unitOfWork.SaveChange();
            foreach (var item in Carts)
            {
                _unitOfWork.OrderDetailRepository.Add(new OrderDetail
                {
                    OrderId = order.OrderId,
                    BookId = item.BookId,
                    Quantity = item.Quantity
                });
                _unitOfWork.SaveChange();

            }
            _unitOfWork.CartRepository.DeleteAllByUserId(HttpContext.Session.GetInt32("userid").Value);
            HttpContext.Session.SetInt32("cartcount", 0);
            _unitOfWork.SaveChange();

            return RedirectToPage("Index");
        }
    }
}

Library/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Library.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Library/Pages/Index.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IList<Category> Categories { get; set; }
        public IList<LibraryCore.Models.Book> Book { get; set; }
        public void OnGet()
        {

            Categories = _unitOfWork.CategoryRepository.GetAll();
            Book = _unitOfWork.BookRepository.GetAll().Where(x => x.Status.Value).ToList();
        }
    }
}

Library/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using LibraryCore.Models;
using LibraryCore.UnitOfWork;

namespace Library.Pages
{
    public class LoginModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public LoginModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public User User { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            ModelState.Remove("User.Fullname");
            ModelState.Remove("User.Mail");
            ModelState.Remove("User.UserRole");
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = _unitOfWork.UserRepository.GetAll().FirstOrDefault(x => x.Username.Equals(User.Username) && x.Password.Equals(User.Password));
            if (user == null)
            {
                ModelState.AddModelError("wrong","Wrong username or password!");
                return Page();
            }

            if (user.Status == false)
            {
                ModelState.AddModelError("wrong", "Access denied!");
                return Page();

            }
            HttpContext.Session.SetString("username",user.Username);
            HttpContext.Session.SetInt32("userid",user.UserId);
            HttpContext.Session.SetString("role",user.UserRole);
            HttpContext.Session.SetInt32("cartcount",_unitOfWork.CartRepository.FindByUserId(user.UserId).Count);

            return RedirectToPage("Index");
        }
    }
}

Library/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }
    }
}

Library/Pages/Order.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Library.Pages
{
    public class OrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        [BindProperty]
        public IList<Order> Orders { get; set; }


        public OrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult OnGet()
        {
            
            if (HttpContext.Session.GetString("username") == null)
            {
                return RedirectToPage("Index");
            }
            Orders = _unitOfWork.OrderRepository.GetOrderByUserId(HttpContext.Session.GetInt32("userid").Value);
            return Page();

        }
    }
}

Library/Pages/Otp.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class OtpModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public OtpModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public string error { get; set; }
        public void OnGet()
        {

        }
        public IActionResult OnPost(string otpInput)
        {
            string otp = HttpContext.Session.GetString("otp");
            string idRegister = HttpContext.Session.GetString("idRegister");
            string account = HttpContext.Session.GetString("account");

            if (otpInput != null && otpInput == otp)
            {
                if (idRegister != null)
                {

                    User u = _unitOfWork.UserRepository.Find(int.Parse(idRegister));
                    u.Status = true;
                    _unitOfWork.UserRepository.Update(u);
                    _unitOfWork.SaveChange();
                    HttpContext.Session.SetString("message", "Register sucessfully");
                    return RedirectToPage("/Login");
                }
                /*if (account != null)
                {
                    User u = _unitOfWork.UserRepository.FindUserByName(account);
                    u.Status = true;
                    u.Password = otp;

                    _unitOfWork.UserRepository.Update(u);
                    _unitOfWork.SaveChange();
                    HttpContext.Session.SetString("message", "New password was send to your email");
                    return RedirectToPage("/Login");
                }*/
            }

            error = "Wrong otp";
            return Page();

        }

    }
}

Library/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Library/Pages/Profile.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Library.Pages
{
    public class ProfileModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public ProfileModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public string status { get; set; } = "1";
        public User user { get; set; }
        public string mess { get; set; }
        public IActionResult OnGet(string st)
        {
            if (st != null)
            {
                status = st;
            }

            int id = (int)HttpContext.Session.GetInt32("userid");
            user = _unitOfWork.UserRepository.Find(id);

            return Page();
        }

        public IActionResult OnPost(string fullname, string password, string cfPassword,string st)
        {
            int id = (int)HttpContext.Session.GetInt32("userid");
            user = _unitOfWork.UserRepository.Find(id);
            if (st == "1")
            {
                status = st;
                user.Fullname = fullname;
                mess = "Update infomation success";
            }
            else if (st == "2")
            {
                status = st;
                if (password == cfPassword)
                {
                    user.Password = password;
                    mess = "Update infomation success";
                }
                else
                {
                    mess = "Password and re-password not match";
                }
            }
            _unitOfWork.UserRepository.Update(user);
            _unitOfWork.SaveChange();

            

            return Page();
        }
    }
}

Library/Pages/RePassword.cshtml.cs
using LibraryCore.Models;
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Principal;

namespace Library.Pages
{
    public class RePasswordModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly IEmailSender _emailSender;

        public RePasswordModel(IUnitOfWork unitOfWork, IEmailSender emailSender)
        {
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }
        public bool check { get; set; } = false;
        public string error { get; set; }

        public void OnGet()
        {
           
        }

        public IActionResult OnPost(string account)
        {
            string otp = _emailSender.GetOTP();
            User user = _unitOfWork.UserRepository.FindUserByName(account);

            string mailBody = $"<h4>Thank you for used an account on our website.</h4>" +
                $"<p>Here is your new password: {otp}</p>" +
                $"<img src='https://th.bing.com/th/id/OIP.Sbr17XYoywddAYpXUY_f-gHaEm?w=274&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7'/>";
            bool sendMailCheck = _emailSender.SendEmail(user.Mail, "Rest password OTP", mailBody);
            
            check = true;
            if (sendMailCheck)
            {
                user.Status = true;
                user.Password = otp;
                _unitOfWork.UserRepository.Update(user);
                _unitOfWork.SaveChange();
                HttpContext.Session.SetString("message", "New password was send to your email");
                return RedirectToPage("/Login");
            }

            error = "Email not exsist";

            return Page();
        }
    }
}

Library/Pages/Register.cshtml.cs
using LibraryCore.UnitOfWork;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using LibraryCore.Models;
using Microsoft.AspNetCore.Http;

namespace Library.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly IEmailSender _emailSender;

        public RegisterModel(IUnitOfWork unitOfWork, IEmailSender emailSender)
        {
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
        }
        public IActionResult OnGet()
        {
            return Page();
        }

        public bool check { get; set; } = false;
        public string error { get; set; }
        public IActionResult OnPost(string fullName, string account, string password, string cfPassword, string toEmail)
        {

            if(password!=cfPassword)
            {
                error = "Password and confirmpassword not match";
                return Page();
            }
            else if (_unitOfWork.UserRepository.FindUserByName(account)!=null)
            {
                error = "User name already exsist please input another";
                return Page();
            }
            

            string otp = _emailSender.GetOTP();
            string mailBody = $"<h4>Thank you for registering an account on our website.</h4>" +
                $"<p>Here is your OTP: {otp}</p>" +
                $"<img src='https://th.bing.com/th/id/OIP.Sbr17XYoywddAYpXUY_f-gHaEm?w=274&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7'/>";
            bool sendMailCheck = _emailSender.SendEmail(toEmail, "Register OTP", mailBody);

            User u = new User { Fullname = fullName, Password = password, Username = account, Mail = toEmail, UserRole = "user", Status = false };

            string idRegister =_unitOfWork.UserRepository.AddUser(u);
            check = true;
            if (sendMailCheck)
            {
                HttpContext.Session.SetString("otp", otp);
                HttpContext.Session.SetString("idRegister", idRegister);
                return RedirectToPage("/Otp");
            }

            error = "Email not exsist";

            
            

            return Page();
        }



    }
}

Library/Pages/Cart.cshtml
@page
@model Library.Pages.CartModel
@{
    double total = 0;
}
<style>
    a:hover {
        text-decoration: none
    }
</style>

<div class="card container-fluid pt-5 px-xl-5 pb-3">
    <div class="row">
        <div class="col-md-8 cart">
            <div class="title">
                <div class="row">
                    <div class="col"><h4><b>Shopping Cart</b></h4></div>
                    <div id="countitemleft" class="col align-self-center text-right text-muted">@Model.Carts.Count items</div>
                </div>
            </div>
            @foreach (var item in Model.Carts)
            {
                <div class="row border-top border-bottom">
                    <div class="row main align-items-center">
                        <div class="col-2"><img class="img-fluid" src="@item.Book.Image"></div>
                        <div class="col">
                            <div class="row text-muted">@item.Book.Title</div>
                            <div class="row">@item.Book.Category.CategoryName</div>
                        </div>
                        <div class="col">
                            <a class="btnMinusQuantity" href="#" data-target="@item.CartId">-</a>
                            <a href="#" class="border px-1 mx-1 quantity">@item.Quantity</a>
                            <a class="btnAddQuantity" href="#" data-target="@item.CartId">+</a>
                        </div>
                        <div class="col">&euro; @item.Book.Price <a asp-page="/Cart" asp-page-handler="DeleteCart" asp-route-cartId="@item.CartId" class="close">&#10005;</a></div>
                        @{
                            total += item.Book.Price.Value * item.Quantity;
                        }
                    </div>
                </div>


            }

            <div class="back-to-shop"><a href="#">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
        </div>
        <div class="col-md-4 summary">
            <div><h5><b>Summary</b></h5></div>
            <hr>
            <div class="row mb-3">
                <div class="col" id="countitemright"/>ITEMS @Model.Carts.Count</div>
                <div class="col text-right" id="itemprice">&euro; @total.ToString("F2")</div>
            </div>
            <form method="POST">
                <p>Shipping</p>
                <select class="w-100 p-2 mb-3" id="select-option" onchange="updateValue()">
                    <option class="text-muted" value="5">Standard Delivery - &euro;5.00</option>
                    <option class="text-muted" value="10">High Quality Delivery - &euro;10.00</option>
                </select>
                <p>Address</p>
                <input required class="w-100 p-2 mb-3" asp-for="Address" placeholder="Enter your address">
                <hr>
                <div class="row" style="padding: 2vh 0;">
                    <div class="col fw-bolder">TOTAL PRICE</div>
                    <div id="total" class="col text-right fw-bolder">&euro;</div>
                    <input type="hidden" id="totalhidden" asp-for="Total" value="" />
                </div>
                <button class="btn btn-primary w-100">CHECKOUT</button>
            </form>

        </div>
    </div>


<script>
    let initialValueStr = document.getElementById("total")
    var x = parseFloat($('#itemprice').text().split(' ')[1])

    let total = document.getElementById("totalhidden")
    total.value = x.toFixed(2)
    console.log(total.value)
    initialValueStr.innerHTML = "&euro; " + (x + parseFloat($("#select-option").val())).toFixed(2)

    function updateValue() {
        x = parseFloat($('#itemprice').text().split(' ')[1])
        let selectedValue = parseInt(document.getElementById("select-option").value);
        total.value = (x - 5 + selectedValue).toFixed(2)
        console.log(total.value)
        document.getElementById("total").innerHTML = "&euro; " + (x + selectedValue).toFixed(2);
    }
</script>
<script>
    $(document).ready(function () {
        $('.btnAddQuantity').click(function (e) {
            e.preventDefault();
            var targetId = $(this).data('target');
            var quantity = $(this).parent().find('.quantity');
            $.ajax({
                type: 'GET',
                url: '/Cart?handler=AddQuantity&cartId=' + targetId,
                dataType: 'json',
                success: function (data) {
                    quantity.empty();
                    if (data) {
                        quantity.append(data.quantity);
                        var x = parseFloat($('#itemprice').text().split(' ')[1])
                        x = x + data.book.price
                        $('#itemprice').text("€ " + x.toFixed(2))
                        $('#total').text("€ " + (x + parseFloat($("#select-option").val())))
                        $('#totalhidden').value = x + parseFloat($("#select-option").val())
                    } else {
                        $('#dataContainer').text('No data available.');
                    }
                },
                error: function () {
                    $('#dataContainer').text('Error occurred while loading data.');
                }
            });
        });
    });

    $(document).ready(function () {
        $('.btnMinusQuantity').click(function (e) {
            e.preventDefault();
            var targetId = $(this).data('target');
            var quantity = $(this).parent().find('.quantity');
            $.ajax({
                type: 'GET',
                url: '/Cart?handler=MinusQuantity&cartId=' + targetId,
                dataType: 'json',
                success: function (data) {
                    quantity.empty();
                    if (data) {
                        if (data.quantity == 0) {
                            quantity.closest('.row.border-top.border-bottom').remove();
                            $('#cartcounting').text($('#cartcounting').text()-1);
                            $('#countitemleft').text($('#countitemleft').text()[0]-1 +" items")
                            var countitemrighttext = $('#countitemright').text().split(' ');
                            var update = countitemrighttext[1] - 1
                            $('#countitemright').text("ITEMS " + update);

                        }
                        else {
                        quantity.append(data.quantity);
                        }
                        var x = parseFloat($('#itemprice').text().split(' ')[1])
                        x = x - data.book.price
                        $('#itemprice').text("€ " + x.toFixed(2))
                        $('#total').text("€ " + (x + parseFloat($("#select-option").val())))
                        $('#totalhidden').value = x + parseFloat($("#select-option").val())
                    } else {
                        $('#dataContainer').text('No data available.');
                    }
                },
                error: function () {
                    $('#dataContainer').text('Error occurred while loading data.');
                }
            });
        });
    });
</script>

Library/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<div class="container-fluid pt-5">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Categories</span></h2>
    <div class="row px-xl-5 pb-3">
        
        @foreach (var item in Model.Categories)
        {
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <a class="text-decoration-none" asp-page="/Book/Search" asp-route-cid="@item.CategoryId">
                    <div class="cat-item d-flex align-items-center mb-4">
                        <div class="overflow-hidden" style="width: 100px; height: 100px;">
                            <img class="img-fluid h-100" src="@item.Image" alt="">
                        </div>
                        <div class="flex-fill pl-3">
                            <h4>@item.CategoryName</h4>
                            <small class="text-body">@item.Books.Where(x=>x.Status.Value).ToList().Count books</small>
                        </div>
                    </div>
                </a>
            </div>

        }
    </div>
</div>
<!-- Products Start -->
<div class="container-fluid pt-5 pb-3">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Featured Products</span></h2>
    <div class="row px-xl-5">
        @foreach(var item in Model.Book){
                <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                    <div class="product-item bg-light mb-4">
                        <div class="product-img position-relative overflow-hidden">
                            <a asp-page="/Book/Detail" asp-route-id="@item.BookId"><img class="img-fluid w-100" src="@item.Image" alt=""></a>

                        </div>
                        <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" asp-page="/Book/Detail" asp-route-id="@item.BookId">@item.Title</a>
                            <div class="d-flex align-items-center justify-content-center mt-2">
                                <h5>By @item.Author.Fullname</h5>
                            </div>
                            <div class="d-flex align-items-center justify-content-center mt-2">
                                @for(int i = 1 ; i <= item.Rate ; i++) {
                                
                                    <small class="fa fa-star text-primary mr-1"></small>
                            }
                            </div>
                            <div class="d-flex align-items-center justify-content-center mt-2">
                                <small>@item.Quantity left</small>
                            </div>
                        </div>


                    </div>
                </div>
        }
    </div>
</div>
<!-- Products End -->

Library/Pages/Login.cshtml
@page
@model Library.Pages.LoginModel

@{
    ViewData["Title"] = "Login";
    Layout = "";

    string mess = (string)HttpContext.Session.GetString("message");
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/0beab2041e.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <style>
        .bg-image-vertical {
            position: relative;
            overflow: hidden;
            background-repeat: no-repeat;
            background-position: right center;
            background-size: auto 100%;
        }

        @@media (min-width: 1025px) {
            .h-custom-2 {
                height: 100%;
            }
        }
    </style>
</head>

<body>
    <section class="vh-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">

                    <div class="px-5 ms-xl-4">
                        <i class="fas fa-crow fa-2x me-3 pt-5 mt-xl-4" style="color: #709085;"></i>
                        <span class="h1 fw-bold mb-0">Book Shop</span>
                    </div>

                    <div class="d-flex align-items-center px-5 ms-xl-4 mt-5 pt-5 pt-xl-0 mt-xl-n5">
                        <form style="width: 23rem;" asp-page="Login">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <h3 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Log in</h3>
                            <h5 class="text-danger">@Html.ValidationMessage("wrong")</h5>

                            <h5 class="text-danger">@mess</h5>

                            <div class="form-outline mb-4">
                                <label asp-for="User.Username" class="control-label"></label>
                                <input asp-for="User.Username" class="form-control form-control-lg" />
                                <span asp-validation-for="User.Username" class="text-danger"></span>
                            </div>

                            <div class="form-outline mb-4">
                                <label asp-for="User.Password" class="control-label"></label>
                                <input asp-for="User.Password" class="form-control form-control-lg" />
                                <span asp-validation-for="User.Password" class="text-danger"></span>
                            </div>

                            <div class="form-outline mb-4 d-flex">
                                <label class="control-label p-2"><a href="/Register">Register</a></label>
                                <label class="control-label p-2"><a href="/RePassword">Forget password</a></label>
                            </div>


                            <div class="pt-3 mb-4">
                                <input type="submit" value="Login" class="btn btn-info btn-lg btn-block" />
                            </div>
                        </form>
                    </div>
                    



                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img3.webp"
                         alt="Login image" class="w-100 vh-100" style="object-fit: cover; object-position: left;">
                </div>
            </div>
        </div>
    </section>
</body>

</html>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

Library/Pages/Logout.cshtml
@page
@model Library.Pages.LogoutModel
@{
}